apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup-resources
      image: alpine:latest
      script:
        - echo "Cleaning up resources"
        - echo "Running additional cleanup tasks here"
        - echo "Done with cleanup"

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  steps:
    - name: run-nose-tests
      image: python:3.9
      script:
        - pip install nose
        - pip install coverage
        - echo "Running nose tests with coverage"
        - nosetests --with-coverage --cover-package=app --cover-xml --cover-html --verbosity=2